# Generated by Django 5.1.7 on 2025-03-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_nfc',
            field=models.BooleanField(default=False),
        ),
    ]
