# Generated by Django 5.1.7 on 2025-03-29 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='secure_key',
            field=models.CharField(default='812752ceacda4bfb', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('outlet', 'Outlet'), ('admin', 'Admin')], default='outlet', max_length=10),
        ),
    ]
