# Generated by Django 5.1.7 on 2025-03-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='secure_key',
            field=models.CharField(default='10f6e0d770f7412f', max_length=16, unique=True),
        ),
    ]
