# Generated by Django 5.1.7 on 2025-03-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_card_secure_key_alter_card_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='activation_date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='block_reason',
        ),
        migrations.RemoveField(
            model_name='card',
            name='daily_limit',
        ),
        migrations.RemoveField(
            model_name='card',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='card',
            name='last_used',
        ),
        migrations.RemoveField(
            model_name='card',
            name='transaction_limit',
        ),
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
        migrations.AlterField(
            model_name='card',
            name='secure_key',
            field=models.CharField(default='51d7a3b6668d438c', max_length=16, unique=True),
        ),
    ]
